---
knowbe4_api_key: "{{ lookup('env', 'KNOWBE4_API_KEY') }}"
rapid7_api_key: "{{ lookup('env', 'RAPID7_API_KEY') }}"
zscaler_api_key: "{{ lookup('env', 'ZSCALER_API_KEY') }}"
cloudflare_api_key: "{{ lookup('env', 'CLOUDFLARE_API_KEY') }}"
meraki_api_key: "{{ lookup('env', 'MERAKI_API_KEY') }}"
slack_webhook_url: "{{ lookup('env', 'SLACK_WEBHOOK_URL') }}"
discord_webhook_url: "{{ lookup('env', 'DISCORD_WEBHOOK_URL') }}"
notify_email: "{{ lookup('env', 'NOTIFY_EMAIL') }}"
smtp_server: "{{ lookup('env', 'SMTP_SERVER') }}"
smtp_port: "{{ lookup('env', 'SMTP_PORT') }}"
backup_link: '{{ lookup("env", "BACKUP_LINK") }}'
